theme_color:
  primary: indigo
  accent: blue

notice: 
  - "è¯¥ç«™ç‚¹å°šåœ¨å»ºè®¾ä¸­ã€‚é‡åˆ°é—®é¢˜è¯·<a target='_blank' href='//github.com/SteveZMTstudios/articles/issues/new/choose'>åé¦ˆç»™æˆ‘ä»¬</a>ï¼"
  - "????!!!!!??!?!?!??!?!?!!!!"
  - "è¯·å°† busuanzi.ibruce.info æ·»åŠ åˆ°æ‚¨çš„ uBlock Origin ä¾‹å¤–åˆ—è¡¨ä¸­ï¼"
  - "æˆ‘æ˜¯ä¸€ä¸ªæ‡’äººï¼Œæ‰€ä»¥è¿™ä¸ªç«™ç‚¹å¯èƒ½ä¼šå¾ˆä¹…æ‰æ›´æ–°ä¸€æ¬¡ã€‚"
  - "è¿™ä¸ªåšå®¢åŸºæœ¬ä¸Šæ‰€æœ‰çš„ç²¾åŠ›éƒ½èŠ±åœ¨åˆ€æŠŠä¸Šäº†..."
  - "â€œå®‡å®™å°æœºå™¨äººæ˜¯ä»€ä¹ˆç©æ„â€"
  - "// TODO"
  - "æˆ‘å¾ˆå¯çˆ±è¯·<a target='_blank' href='//space.bilibili.com/474130186'>ç»™æˆ‘é’±</a>qwq"
  - "console.log('Hello World!')"
  - "æˆ˜ç¥èµ·è·³ï¼Œæˆ˜ç¥ç¡è§‰"
  - "å–µï¼"
  - "æ­ªæ¯”å·´åœ"
  - "å†·çŸ¥è¯†â€”â€”â€”é˜¿åšï¼"
  - "ğŸ¥µ...çƒ­çŸ¥è¯†..."
  - "ç¥è¦æ˜¯å…¬ç„¶å»è·Ÿäººä½œå¯¹ï¼Œé‚£æ˜¯ä»»ä½•äººéƒ½éš¾ä»¥å¯¹ä»˜çš„ã€‚ â€”â€”ã€Šè·é©¬å²è¯—ã€‹"
  - "1 2 4 8 16 32 64 128 256 512 1024 2048 4096 8192 16384 32768 65536..."
  - "ç«™é•¿é—²ç€æ— èŠæ“äº†ä¸€ä¸ª<a target='_blank' href='/new'>é¡µé¢åˆ›å»ºå™¨</a>ï¼ŒçœŸçš„å¾—å«ä»–æ‰¾ä¸ªç­ä¸Šäº†..."
  - "å…¶å®404é¡µé¢æœ‰ä¸ªåœ°æ–¹èƒ½ç‚¹ï¼Œç”¨é¼ æ ‡æ™ƒæ™ƒå°±èƒ½æ‰¾åˆ°ï¼ˆ"
  - "ä¸è¦è¯•å›¾ä»¥phpä¸ºurlç»“å°¾è®¿é—®æœ¬ç«™ã€‚æœ¬ç«™æ²¡æœ‰ä½¿ç”¨ä»»ä½•phpé¡µé¢ã€‚"
  - "è‡´ä¸€ä½å‹¤åŠ³çš„ä¿„ç½—æ–¯é»‘å®¢ï¼šæœ¬åšå®¢çœŸçš„æ²¡æœ‰ä½¿ç”¨WordPress..."
  - "æœ¬ç«™ç‚¹ä¸æ”¯æŒIEæµè§ˆå™¨ã€‚ï¼ˆçœŸçš„å—ï¼Ÿï¼‰"
  - "æ³¼å‡ºå»çš„æ°´ï¼Œæˆ‘è¿ç›†éƒ½ä¸è¦ï¼ˆ"
  - "â€œå¸ˆå‚…ï¼Œæ•™æˆ‘åˆ†èº«æœ¯å§ã€‚â€â€œé¦–å…ˆï¼Œä½ è¦æœ‰æŠŠç”µé”¯ã€‚ã€‚ã€‚â€ï¼ˆ"
  - "â€œä½ æ˜¯ä¸€ä¸ªå¾ˆå¥½å¥‡çš„äººâ€â€œä¸ºä»€ä¹ˆè¿™ä¹ˆè¯´ï¼Ÿâ€â€œä½ çœ‹ä½ åˆé—®äº†â€"
  - "äººç±»æ¯å¤©éƒ½ç›–è¢«å­ç¡è§‰ï¼Œæ‰€ä»¥äººç±»æ˜¯è¢«å­æ¤ç‰©ã€‚"
  - "äººå¾€é«˜å¤„èµ°ï¼Œæ°´å¾€ä½å¤„æµï¼Œäººçš„80%æ˜¯æ°´ï¼Œæ‰€ä»¥å¤§éƒ¨åˆ†äººå°±ç®—åˆ°äº†é«˜å¤„ä¹Ÿè¿˜æ˜¯ä¸‹æµçš„ï¼ˆx"
  - "å¥¶ç‰›çš„è‹±æ–‡æ˜¯cowï¼Œæ‰€ä»¥ç‰›å¥¶çš„è‹±æ–‡æ˜¯wocï¼ˆ"
  - "å¤§è‹±åšç‰©é¦†å‘ç”Ÿä¸¥é‡ç›—çªƒæ¡ˆï¼Œè´Ÿè´£äººå‘æ–‡å“­è¯‰åŒè¡Œå†…å·ã€‚"
  - "â€œæˆ‘çš„æ³•åŠ›ä¸æ¯”å¦‚æ¥ä½›å·®ï¼Œä½ æ˜¯æ€ä¹ˆé€ƒå‡ºæˆ‘çš„æ‰‹æŒå¿ƒçš„?â€è€¶ç¨£ä¸è§£åœ°é—®å­™æ‚Ÿç©ºï¼ˆ"
  - "â€œæ‰“ä»—æ‰“çš„å°±æ˜¯åå‹¤â€è¯´ç½¢ç‹å°†å†›ä»¤äººå°†å¨å¸ˆå¡è¿›ç‚®ç­’ï¼ˆ"
  - "æˆ‘æ€€ç–‘é‚£äº›æ–°é—»è®°è€…éƒ½æ˜¯æœºå™¨äººï¼Œä¸ç„¶ä¸ºå•¥è‡ªç§°â€œæœ¬å°è®°è€…â€ï¼ˆ"
  - "ç‹è€æ±‰æ‰¾äººæ‹¼å‘½ï¼Œç°åœ¨ä¸¤äººå…±ç”¨ä¸€æ¡å‘½ï¼ˆ"
  - "ç‹è­¦å®˜åœ¨ç°åœºå‹˜å¯Ÿäº†4ä¸ªå°æ—¶ï¼Œç»ˆäºå‘ç°äº†æ¡ˆä»¶è¿˜æ²¡æœ‰å‘ç”Ÿï¼ˆ"
  - "åŒ»ç”Ÿè¯´:â€œåƒç‚¹å¥½çš„ã€‚â€äºæ˜¯æˆ‘æŠŠæˆ‘åœ¨å·¥ä½œç¾¤çš„å›å¤éƒ½åƒäº†ï¼ˆ"
  - "é•‡å…³è¥¿æŒ¨äº†ä¸‰æ‹³åå¿ƒé¢†ç¥ä¼šï¼Œæ™šä¸Šä¸‰æ›´å‡†æ—¶æ¥åˆ°é²æè¾–çš„æˆ¿é—´ï¼ˆ"
  - "çš‡å¸æ„Ÿå¹é“ï¼šâ€œå­¤çš„èƒœï¼Œä½ ä»¬éƒ½çœ‹åœ¨çœ¼é‡Œï¼›å­¤çš„è´¥ã€‚â€ç„¶åå°±é€€æœäº†ï¼ˆ"
  - "ä¸ˆå¤«è‡ªç§°é¾™çš„ä¼ äººï¼Œä¸æ–™å¦»å­ç«Ÿç”Ÿä¸‹ä¸ªé»‘å®å®ã€‚åšå®Œäº²å­é‰´å®šè™šæƒŠä¸€åœºï¼ŒåŸæ¥æ˜¯ä¸ªä¹Œé¾™"
  - "â€œèˆå‹ä¸€å‘¨ä¸æ´—æ¾¡ï¼Œèº«ä¸Šéƒ½è‡­äº†ï¼Œæ˜¯ä¸æ˜¯ä»–è¿˜åœ¨ç”Ÿæˆ‘ä¸Šå‘¨ç äº†ä»–ä¸€åˆ€çš„æ°”ï¼Ÿâ€"
  - "è€è‡£å¹´è¿ˆï¼Œæ— æ³•è·ªè°¢çš‡æ©ï¼Œåªå¥½æ–°è‡£ä»£è°¢ï¼ˆ"
  - "åœ°çƒä¸Šæœ‰70%çš„æµ·æ´‹å’Œ30%çš„é™†åœ°ï¼Œé‚£ä¹ˆå‰©ä¸‹çš„30%æµ·æ´‹å’Œ70%çš„é™†åœ°å»å“ªäº†ï¼Ÿ"
  - "åˆ˜å¤‡è¢«ç§°èµçˆ±æ°‘å¦‚å­ï¼Œå°†å›´è§‚ç¾¤ä¼—æŒ¨ä¸ªæ‘”å€’åœ¨åœ°ã€‚"
  - "â€œä½ æ—¥åè¦æ˜¯æƒ¹å‡ºç¥¸æ¥ï¼Œå¸ˆçˆ¶çš„åå­—å°±ä¸è¦æäº†ã€‚â€è©ç¥–å¸ˆå¯¹å­™æ‚Ÿç©ºè¯´ï¼ˆ"
  - "â€œå˜å½¢é‡‘åˆšå¯‚å¯äº†ä¼šä¸Šç½‘çº¦è½¦å—ï¼Ÿâ€"
  - "è°ˆåˆ¤ä¸“å®¶å–Šè¯è¯¢é—®è¢«æ­¹å¾’ç»‘æ¶çš„äººè´¨æ•°æ˜¯å¤šå°‘ï¼Œä¸ä¹…åå¬åˆ°å›åº”:â€œ2ï¼Œ3ï¼Œ5ï¼Œ7ï¼Œ11...â€"
  - "ä½ è¿™è¾ˆå­å°±æ˜¯è¢«å’•å’•åå®³äº†ã€‚"
  - "ä½ çŒœçŒœè¿˜è¦åˆ·å¤šå°‘éæ‰èƒ½åˆ·åˆ°è¿™æ¡~"
  - "ä¸€ä¸ªåŠå°æ—¶æ˜¯ä¸‰ä¸ªåŠå°æ—¶ï¼ˆ"
  - "ã€Šä½ çš„è„‘è¢‹æ€ä¹ˆå°–å°–çš„ã€‹"
  - "Jeff Dean ç©¿è£¤å­æ—¶ä¸€æ¡è…¿ä¸€æ¡è…¿åœ°ç©¿ï¼Œä½†å¦‚æœä»–æœ‰ä¸¤æ¡ä»¥ä¸Šçš„è…¿ï¼Œä½ å°±ä¼šå‘ç°ä»–çš„æ–¹æ³•å®é™…ä¸Šæ˜¯O(log n)â€¦â€¦"
  - "ä¸ºä»€ä¹ˆç¨‹åºå‘˜å–œæ¬¢åœ¨æ²™æ»©ä¸Šå·¥ä½œï¼Ÿå› ä¸ºé‚£é‡Œæœ‰å¾ˆå¤šshell("
  - "ä¸ºä»€ä¹ˆç¨‹åºå‘˜æ€»æ˜¯åˆ†ä¸æ¸…ä¸‡åœ£èŠ‚å’Œåœ£è¯èŠ‚ï¼Ÿå› ä¸º <span title='å…«è¿›åˆ¶31 = åè¿›åˆ¶25,è¿™ç”šè‡³éƒ½ä¸èƒ½ç®—æ˜¯ä¸ªç¬‘è¯'>Oct 31 == Dec 25</span>"
  - "åœ¨å…­æœˆï¼ŒçŸ¥åé»‘å®¢â€œå­™å†›â€åœ¨å„ä¸ªSSHæœåŠ¡å™¨ä¸Šç•™ä¸‹äº†è‡ªå·±çš„åå­—(Sun Jun)ï¼Œä»¥è¯æ˜å…¶å­˜åœ¨"
  - "Jeff Deançš„é“¶è¡Œå¡å¯†ç æ˜¯åœ†å‘¨ç‡çš„æœ€åå››ä½ã€‚"
  - "Jeff Deanåœ¨æ–¯å¦ç¦æ¼”è®²æ—¶ï¼Œåœºåœºçˆ†æ»¡ï¼Œè¿å”çº³å¾·Â·å…‹åŠªç‰¹éƒ½åªèƒ½å¸­åœ°è€Œåã€‚(<span title='ä½ å¯ä»¥åœ¨youtubeç­‰å¹³å°æ‰¾åˆ°å½•åƒæ£€æŸ¥è¿™ä¸€ç‚¹'>ç¡®æœ‰å…¶äº‹</span>)"
  - "åœ¨æœ€é«˜èŒçº§ä¸º10çº§çš„ä½“ç³»é‡Œï¼ŒJeff Deanæ™‹å‡è‡³11çº§ã€‚(<span title='ä¸ºäº†ææ‹” Jeffï¼ˆå’Œ Sanjayï¼‰ï¼Œä»–ä»¬ä¸å¾—ä¸è®¾ç«‹ä¸€ä¸ªæ–°èŒä½ï¼ˆé«˜çº§ Google ç ”ç©¶å‘˜ï¼‰ã€‚'>ç¡®æœ‰å…¶äº‹</span>)"
  - "ä½ çš„å¤§è„‘ä»…å¼€å‘10%ï¼Œå…¶ä½™90%éƒ½åœ¨è¿è¡ŒJeffçš„MapReduceä»»åŠ¡ã€‚"
  - "Jeff Dean çš„ç®€å†ç½—åˆ—çš„æ˜¯ä»–è¿˜æ²¡åšè¿‡çš„äº‹æƒ…ï¼›è¿™æ ·å†™èµ·æ¥æ›´çœç¯‡å¹…ã€‚"
  - "æœ‰ä¸€å¤©ï¼ŒJeff Dean è¢«è¿«å‘æ˜äº†å¼‚æ­¥ APIï¼Œåªå› ä»–æŠŠä¸€ä¸ªå‡½æ•°ä¼˜åŒ–åˆ°èƒ½åœ¨è¢«è°ƒç”¨ä¹‹å‰å°±è¿”å›ã€‚"
  - "Jeff Dean ä¸ç”¨ ECC å†…å­˜ã€‚ä»–èƒ½é¢„çŸ¥å®‡å®™å°„çº¿ï¼Œå¹¶åˆ©ç”¨å®ƒä»¬æ¥æå‡æ€§èƒ½ã€‚"
  - "è°·æ­Œï¼šåŸºæœ¬ä¸Šå°±æ˜¯ Jeff Dean çš„ä¸€ä¸ªä¸šä½™é¡¹ç›®ã€‚"
  - "2000 å¹´åº•ï¼Œå½“ Jeff Dean å°†é”®ç›˜å‡çº§åˆ° USB 2.0 åï¼Œä»–çš„ä»£ç äº§å‡ºæ•ˆç‡ç¬é—´æå‡äº† 40 å€ã€‚"
  - "Jeff Deanå¯ä»¥é€šè¿‡æŠŠç¡¬ä»¶æ‰”åˆ°åœ°ä¸Šæ¥ä¼˜åŒ–å®ƒçš„æ€§èƒ½ã€‚(<span title='äº‹æƒ…æ˜¯è¿™æ ·çš„ï¼Œæ°å¤«æ­£åœ¨åšæ¼”ç¤ºï¼Œä¸å°å¿ƒæŠŠå¹»ç¯ç‰‡é¥æ§å™¨æ‰åœ¨äº†åœ°ä¸Šï¼Œç›–å­å¼¹å¼€äº†ï¼Œç”µæ± æ‰äº†å‡ºæ¥ã€‚ä»–æ¡èµ·ç¢ç‰‡ï¼Œé‡æ–°ç»„è£…å¥½ï¼Œä¿®å¥½äº†é¥æ§å™¨ï¼Œç„¶åè¯´ï¼šâ€œå“¦ï¼Œè¿˜æœ‰ä¸€ä¸ªå¤šä½™çš„é›¶ä»¶æˆ‘ä¸éœ€è¦ã€‚â€'>ç¡®æœ‰å…¶äº‹</span>)"
  - "Jeffæ‹¥æœ‰çš„æ ¸å¼¹å¤´ä¸åˆ°10æš(<a href='https://joshdance.medium.com/who-is-jeff-and-why-does-he-have-nuclear-weapons-f823de764c5e' target='_blank'>??</a>)"
  - "æ—ä¸­åˆ†å‰äº†ä¸¤æ¡è·¯ï¼ŒJeff Deanå…¨é€‰äº†ã€‚"
  - "å¥½å§ï¼Œè¿™äº›ç¬‘è¯ä¸å¥½ç¬‘"
  - "å…³äºå¸ƒå°”æ•°æœ€æ£’çš„äº‹æƒ…æ˜¯ï¼Œå°±ç®—ä½ é”™äº†ï¼Œä½ ä¹Ÿåªæ˜¯é”™äº†ä¸€ç‚¹ï¼ˆbitï¼‰ã€‚"
  - "æœ‰ä¸¤ç§æ–¹æ³•å†™å‡ºé›¶é”™è¯¯çš„ç¨‹åºï¼Œåªæœ‰ç¬¬ä¸‰ç§æ–¹æ³•å¥æ•ˆã€‚"
  - 



favicon: /images/favicon.png
banner: /images/banner.png
avatar: /images/avatar.jpg@128x128.jpg
rss: /atom.xml

email: admin@stevezmt.top
sns:
  twitter:
  facebook:
  google_plus:
  steam: //steamcommunity.com/id/stevezmt/
  weibo:
  instagram:
  tumblr:
  github: //github.com/stevezmtstudios/
  linkedin:
  zhihu: //www.zhihu.com/people/zhang-xian-sheng-70-9
  douban:
  qq: tencent://message/?uin=3579946866&Menu=yes
  wechat:
  bilibili: //space.bilibili.com/474130186
  custom: //stevezmt.top/

open_graph:
  twitter:
  google_plus:
  fb_admins:
  fb_app_id:
site_verification:
  google:
  baidu:
analytics:
  google_site_id: G-T404DHJEEZ
  baidu_site_id:
  cnzz_site_id:

pages:
- name: æ—¶é—´è½´
  link: /timeline
- name: æ ‡ç­¾äº‘
  link: /tagcloud
- name: å‹æƒ…é“¾æ¥
  link: /friends
- name: å…¼å®¹è§†å›¾
  link: /k

links:
  - name: å²è’‚å¤«ZMT ä¸»é¡µ
    link: //stevezmt.top/
  - name: Phigros å†å²ç‰ˆæœ¬æ”¶é›†
    link: //stevezmt.top/Phigros-history/
  - name: è¿‡æ°”é¡¹ç›®å­˜æ¡£
    link: //rip.stevezmt.top

    

since: 2019
footer_text: '| <a href="//icp.gov.moe/?keyword=20240571" target="_blank" class="mdui-text-color-theme-accent">èŒICPå¤‡20240571å·</a>'
license: æ­¤é¡µå†…å®¹éµå¾ª<a href="//creativecommons.org/licenses/by-nc-sa/4.0/deed.zh-hans" target="_blank" rel="license noopener noreferrer" style="display:inline-block;"> CC BY-NC-SA 4.0 åè®®</a>

gallery:
  fancybox_css: //gcore.jsdelivr.net/npm/@fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css
  fancybox_js: //gcore.jsdelivr.net/npm/@fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js
  jquery_js: //ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js
  lazyload_js: //gcore.jsdelivr.net/npm/jquery-lazyload@1.9.7/jquery.lazyload.min.js
busuanzi:
  site: true
  page: true
  busuanzi_js: //busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js
qrcode:
  caption: å‘é€åˆ°æ‰‹æœº
  use: plugin
  
donate:
  - name: æ”¯ä»˜å®
    link: /images/page/donate/alipay.jpg
  - name: å¾®ä¿¡
    link: /images/page/donate/wechat.jpg
  - name: Bå¸å……ç”µ
    link: //space.bilibili.com/474130186
  
search:
  placeholder: æœç´¢...
  path: /search.xml
  use: plugin
comment:
  use: gitalk
  disqus_shortname:
  gitalk_client_id: Ov23li2IcxCrL109at0U
  gitalk_client_secret: 6b1433f474c96a5c5a997a1de53739f6f939470a
  gitalk_repo: articles
  gitalk_owner: stevezmtstudios
  gitalk_sid_type: uuid
  livere_data_uid:
  valine_leancloud_app_id:
  valine_leancloud_app_key:
  valine_placeholder:
  valine_page_size:
  valine_avatar:
  valine_lang:
  valine_guest_info:
  valine_notify:
  valine_verify:
  valine_sid_type:
  changyan_app_id:
  changyan_app_key:
  changyan_sid_type:
