theme_color:
  primary: indigo
  accent: blue

notice: 
  - "该站点尚在建设中。遇到问题请<a target='_blank' href='//github.com/SteveZMTstudios/articles/issues/new/choose'>反馈给我们</a>！"
  - "????!!!!!??!?!?!??!?!?!!!!"
  - "请将 busuanzi.ibruce.info 添加到您的 uBlock Origin 例外列表中！"
  - "我是一个懒人，所以这个站点可能会很久才更新一次。"
  - "这个博客基本上所有的精力都花在刀把上了..."
  - "“宇宙小机器人是什么玩意”"
  - "// TODO"
  - "我很可爱请<a target='_blank' href='//space.bilibili.com/474130186'>给我钱</a>qwq"
  - "console.log('Hello World!')"
  - "战神起跳，战神睡觉"
  - "喵！"
  - "歪比巴卜"
  - "冷知识———阿嚏！"
  - "好烫！...热知识"
  - "神要是公然去跟人作对，那是任何人都难以对付的。 ——《荷马史诗》"
  - "1 2 4 8 16 32 64 128 256 512 1024 2048 4096 8192 16384 32768 65536..."
  - "站长闲着无聊搓了一个<a target='_blank' href='/new'>页面创建器</a>，真的得叫他找个班上了..."
  - "其实404页面有个地方能点，用鼠标晃晃就能找到（"
  - "不要试图以php为url结尾访问本站。本站没有使用任何php页面。"
  - "致一位勤劳的俄罗斯黑客：本博客真的没有使用WordPress..."
  - "本站点不支持IE浏览器。（真的吗？）"
  - "泼出去的水，我连盆都不要（"
  - "“师傅，教我分身术吧。”“首先，你要有把电锯。。。”（"
  - "“你是一个很好奇的人”“为什么这么说？”“你看你又问了”"
  - "人类每天都盖被子睡觉，所以人类是被子植物。"
  - "人往高处走，水往低处流，人的80%是水，所以大部分人就算到了高处也还是下流的（x"
  - "奶牛的英文是cow，所以牛奶的英文是woc（"
  - "大英博物馆发生严重盗窃案，负责人发文哭诉同行内卷。"
  - "“我的法力不比如来佛差，你是怎么逃出我的手掌心的?”耶稣不解地问孙悟空（"
  - "“打仗打的就是后勤”说罢王将军令人将厨师塞进炮筒（"
  - "我怀疑那些新闻记者都是机器人，不然为啥自称“本台记者”（"
  - "王老汉找人拼命，现在两人共用一条命（"
  - "王警官在现场勘察了4个小时，终于发现了案件还没有发生（"
  - "医生说:“吃点好的。”于是我把我在工作群的回复都吃了（"
  - "镇关西挨了三拳后心领神会，晚上三更准时来到鲁提辖的房间（"
  - "皇帝感叹道：“孤的胜，你们都看在眼里；孤的败。”然后就退朝了（"
  - "丈夫自称龙的传人，不料妻子竟生下个黑宝宝。做完亲子鉴定虚惊一场，原来是个乌龙"
  - "“舍友一周不洗澡，身上都臭了，是不是他还在生我上周砍了他一刀的气？”"
  - "老臣年迈，无法跪谢皇恩，只好新臣代谢（"
  - "地球上有70%的海洋和30%的陆地，那么剩下的30%海洋和70%的陆地去哪了？"
  - "刘备被称赞爱民如子，将围观群众挨个摔倒在地。"
  - "“你日后要是惹出祸来，师父的名字就不要提了。”菩祖师对孙悟空说（"
  - "“变形金刚寂寞了会上网约车吗？”"
  - "谈判专家喊话询问被歹徒绑架的人质数是多少，不久后听到回应:“2，3，5，7，11...”"
  - "你这辈子就是被咕咕华害了。"
  - "你猜猜还要刷多少遍才能刷到这条~"
  - "一个半小时是三个半小时（"
  - "《你的脑袋怎么尖尖的》"
  - "Jeff Dean 穿裤子时一条腿一条腿地穿，但如果他有两条以上的腿，你就会发现他的方法实际上是O(log n)……"
  - "为什么程序员喜欢在沙滩上工作？因为那里有很多shell("
  - "为什么程序员总是分不清万圣节和圣诞节？因为 <span title='八进制31 = 十进制25,这甚至都不能算是个笑话'>Oct 31 == Dec 25</span>"
  - "在六月，知名黑客“孙军”在各个SSH服务器上留下了自己的名字(Sun Jun)"
  - "Jeff Dean的银行卡密码是圆周率的最后四位。"
  - "Jeff Dean在斯坦福演讲时，场场爆满，连唐纳德·克努特都只能席地而坐。(<span title='你可以在youtube等平台找到录像检查这一点'>确有其事</span>)"
  - "在最高职级为10级的体系里，Jeff Dean晋升至11级。(<span title='为了提拔 Jeff（和 Sanjay），他们不得不设立一个新职位（高级 Google 研究员）。'>确有其事</span>)"
  - "你的大脑仅开发10%，其余90%都在运行Jeff的MapReduce任务。"
  - "Jeff Dean 的简历罗列的是他还没做过的事情；这样写起来更省篇幅。"
  - "有一天，Jeff Dean 被迫发明了异步 API，只因他把一个函数优化到能在被调用之前就返回。"
  - "Jeff Dean 不用 ECC 内存。他能预知宇宙射线，并利用它们来提升性能。"
  - "谷歌：基本上就是 Jeff Dean 的一个业余项目。"
  - "2000 年底，当 Jeff Dean 将键盘升级到 USB 2.0 后，他的代码产出效率瞬间提升了 40 倍。"
  - "Jeff Dean可以通过把硬件扔到地上来优化它的性能。(<span title='事情是这样的，杰夫正在做演示，不小心把幻灯片遥控器掉在了地上，盖子弹开了，电池掉了出来。他捡起碎片，重新组装好，修好了遥控器，然后说：“哦，还有一个多余的零件我不需要。”'>确有其事</span>)"
  - "Jeff拥有的核弹头不到10枚(<a href='https://joshdance.medium.com/who-is-jeff-and-why-does-he-have-nuclear-weapons-f823de764c5e' target='_blank'>??</a>)"
  - "林中分叉了两条路，Jeff Dean全选了。"
  - "好吧，这些笑话不好笑"
  - "关于布尔数最棒的事情是，就算你错了，你也只是错了一点（bit）。"
  - "有两种方法写出零错误的程序，只有第三种方法奏效。"



favicon: /images/favicon.png
banner: /images/banner.png
avatar: /images/avatar.jpg@128x128.jpg
rss: /atom.xml

email: admin@stevezmt.top
sns:
  twitter:
  facebook:
  google_plus:
  steam: //steamcommunity.com/id/stevezmt/
  weibo:
  instagram:
  tumblr:
  github: //github.com/stevezmtstudios/
  linkedin:
  zhihu: //www.zhihu.com/people/zhang-xian-sheng-70-9
  douban:
  qq: tencent://message/?uin=3579946866&Menu=yes
  wechat:
  bilibili: //space.bilibili.com/474130186
  custom: //stevezmt.top/

open_graph:
  twitter:
  google_plus:
  fb_admins:
  fb_app_id:
site_verification:
  google:
  baidu:
analytics:
  google_site_id: G-T404DHJEEZ
  baidu_site_id:
  cnzz_site_id:

pages:
- name: 时间轴
  link: /timeline
- name: 标签云
  link: /tagcloud
- name: 友情链接
  link: /friends
- name: 兼容视图
  link: /k
  target: _blank
- name: 开往
  link: https://www.travellings.cn/go.html
  target: _blank

links:
  - name: 史蒂夫ZMT 主页
    link: //stevezmt.top/
  - name: Phigros 历史版本收集
    link: //stevezmt.top/Phigros-history/
  - name: 过气项目存档
    link: //rip.stevezmt.top

    

since: 2019
footer_text: ' <a href="//icp.gov.moe/?keyword=20240571" target="_blank" class="mdui-text-color-theme-accent"><img style="height:1.5em;vertical-align:middle;" src="https://icp.gov.moe/images/ico64.png"></a> <a href="//beian.miit.gov.cn/#/Integrated/index" target="_blank" class="mdui-text-color-theme-accent">浙ICP备2025213066号</a>'
license: 此页内容遵循<a href="//creativecommons.org/licenses/by-nc-sa/4.0/deed.zh-hans" target="_blank" rel="license noopener noreferrer" style="display:inline-block;"> CC BY-NC-SA 4.0 协议</a>

gallery:
  fancybox_css: //gcore.jsdelivr.net/npm/@fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css
  fancybox_js: //gcore.jsdelivr.net/npm/@fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js
  jquery_js: //ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js
  lazyload_js: //gcore.jsdelivr.net/npm/jquery-lazyload@1.9.7/jquery.lazyload.min.js
busuanzi:
  site: true
  page: true
  busuanzi_js: //busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js
qrcode:
  caption: 发送到手机
  use: plugin
  
donate:
  - name: 支付宝
    link: /images/page/donate/alipay.jpg
  - name: 微信
    link: /images/page/donate/wechat.jpg
  - name: B币充电
    link: //space.bilibili.com/474130186
  
search:
  placeholder: 搜索...
  path: /search.xml
  use: plugin
comment:
  use: gitalk
  disqus_shortname:
  gitalk_client_id: Ov23li2IcxCrL109at0U
  gitalk_client_secret: 6b1433f474c96a5c5a997a1de53739f6f939470a
  gitalk_repo: articles
  gitalk_owner: stevezmtstudios
  gitalk_sid_type: uuid
  livere_data_uid:
  valine_leancloud_app_id:
  valine_leancloud_app_key:
  valine_placeholder:
  valine_page_size:
  valine_avatar:
  valine_lang:
  valine_guest_info:
  valine_notify:
  valine_verify:
  valine_sid_type:
  changyan_app_id:
  changyan_app_key:
  changyan_sid_type:
